spring:
    application:
        name: blog-ui
    thymeleaf:
        mode: LEGACYHTML5
        cache: false

server:
    port: 9700

upload:
    path: http://120.79.249.57:8188/
#eureka:
#    instance:
#        statusPageUrlPath: /info
#        healthCheckUrlPath: /health
#    client:
#        serviceUrl:
#            defaultZone: http://localhost:8761/eureka/